### ISSUE TITLE
"Password" is hashed or otherwise encrypted?

### ISSUE THREAD

**Issue by knice** [ucsc/compromisedaccountdb#1]
I'm one of the admins for the ucsc Github account. I get notified when new repositories are created. When I saw this one, I was intrigued. I looked at all of the code and I see that "password" is a variable that gets checked. I may have missed this when I read through the code in [validation.py](https://github.com/ucsc/compromisedaccountdb/blob/master/validation.py), but I figured I'd ask anyway.

`password` in this context a _hashed_ password string, correct?

**Comment by jkung2314** [comment]
@brhall Feel free to correct me if I'm wrong here. I don't believe ```password``` is a *hashed* password string at this current release. The passwords that are being processed is public information anyways.

**Comment by brhall** [comment]
Hi Rob, this is might be a long-winded response to your question but hopefully worth the extra explanation.

There can be passwords passed into the application via the fileName variable (also a command line option). In that case the application would take in a username/password combination from each line in the file and, if instructed, attempt to bind against an ldap compliant system with that password. The code does not currently handle hashed passwords for the purpose of a bind against an ldap compliant system. 

As @jkung2314 mentioned the data this application processes (typically usernames or username/password combo) come to us as 3rd party notifications about possibly compromised UCSC credentials that have already been posted on the public internet to one or more locations. Those credential dumps are typically unencrypted/unhashed username/password combinations.

In responding to these incidents we attempt to determine a few things before issuing an account reset such as whether the account is active and if the password is legitimate. 

We store these credential dumps in a database because we often find that credential dumps, or portions of them, will circulate around sometimes many months or years after they happen. So it's useful to automate the validation of accounts and know if a current credential dump sent to us was part of a previous credential dump that has already been processed when we make the determination about resets.

Happy to answer any other questions if you have more. Thanks for your interest.

**Comment by knice** [comment]
Ah, I see. Thank you for the thorough response, @brhall ! I appreciate it. That makes sense.

If I understand correctly, this tool takes a list of username/password combinations **already known to be compromised** and tests them against LDAP authentication systems to check for possible matches, which would indicate a username/password combination is still in use and needs to be changed.
